# Generated by Django 4.0 on 2022-05-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oddun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oddun', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('tradicional_ifa', models.TextField()),
                ('nace', models.TextField()),
                ('refranes', models.TextField()),
                ('tratado', models.TextField()),
                ('ebbo', models.TextField()),
                ('ewe', models.TextField()),
                ('ozain', models.TextField()),
                ('eshu', models.TextField()),
                ('patakies', models.TextField()),
            ],
        ),
    ]
